### ISSUE TITLE
SSR Usage instruction missing on README.md

### ISSUE THREAD

**Issue by Beelphegor** [captbaritone/raven-for-redux#102]
Hi, 

I experienced an issue regarding memory leaks when using in combination with server side rendering, and found this issue https://github.com/captbaritone/raven-for-redux/issues/50, which added a warning and some instructions to the README file about this potential issue. 

I think those instructions got lost somehow when merging other changes. This is the original commit https://github.com/captbaritone/raven-for-redux/commit/bc393cfb944aae4e6e0ca3c2d6470ed1ffb7a90b 

Would be nice to add this back :)

Have a nice day,

**Comment by captbaritone** [comment]
Check out https://github.com/vidit-sh/redux-sentry-middleware if you can move to the new Sentry SDK and render each request in a new scope, that should solve your problems!
