### ISSUE TITLE
Sentry discarding invalid parameter 'lastAction'

### ISSUE THREAD

**Issue by joshfarrant** [captbaritone/raven-for-redux#2]
I'm currently swapping out redux-raven-middleware for raven-for-redux (much prefer your implementation :+1: ) and I've just run into this error in Sentry:

`Sentry discarding invalid parameter 'lastAction'`

Not sure if this is actually a bug with this project, but wanted to check if this something you've come across before, or have any thoughts on how to resolve?

**Comment by captbaritone** [comment]
Where exactly are you seeing the error? Sentry.io, or as a console error from Raven?

**Comment by joshfarrant** [comment]
I'm seeing this within Sentry. As I said, it may not strictly be an issue with this project, I just wanted to check whether or not there could be an issue with the way raven-for-redux is formatting the data that Sentry is having difficulty parsing.

If this isn't reproducible (My set-up is identical to that in the README) then it's unlikely that this is an issue with this project and is more likely an issue with my install of Sentry.

**Comment by captbaritone** [comment]
It looks like this was caused by me calling `Raven.context` incorrectly.

I've cut a new release `0.4.0`. Would you try upgrading and see if that fixes the issue?

Thanks for reporting this!

**Comment by joshfarrant** [comment]
All good, thanks for the fix!
