### ISSUE TITLE
add action to breadcrumb

### ISSUE THREAD

**Issue by cyberhck** [captbaritone/raven-for-redux#27]
Add the whole action to breadcrumb. Normally people add payload to their action, this way, we can make a report more "reproducible". I believe right now we're only adding `action.type` in breadcrumb.

**Comment by captbaritone** [comment]
You should be able to achieve something like this with the [breadcrumbdatafromaction](https://github.com/captbaritone/raven-for-redux#breadcrumbdatafromaction-function) option. Keep in mind that it's very easy to run up against the maximum payload size allowed the Sentry. The documentation for the option goes into a bit more detail.

I'll leave this issue open as a reminder to call out this specific use case in the `breadcrumbdatafromaction` documentation.
