### ISSUE TITLE
npm build?

### ISSUE THREAD

**Issue by bjudson** [captbaritone/raven-for-redux#41]
When I pull version 1.1.0 from npm (actually I'm using yarn), the built version of the code (`built/index.js`) doesn't reflect what I'm seeing on GitHub. But the README is up to date.

**Comment by captbaritone** [comment]
Hmm. Maybe the build step didn't run. I'll look this evening. Sorry about that.

**Comment by captbaritone** [comment]
I'm really not sure what happened. I've republished as 1.1.1 and it seems to work now. Would you mind confirming?

**Comment by captbaritone** [comment]
Okay, my hypothesis at this point is that I hadn't rebased from github when I published.

**Comment by bjudson** [comment]
Cool, thanks for the quick fix. Probably pushing this into production today or tomorrow along with React 16.

**Comment by captbaritone** [comment]
Great! Let me know if you hit any snags.
