### ISSUE TITLE
What kind of errors will be captured?

### ISSUE THREAD

**Issue by kontrollanten** [captbaritone/raven-for-redux#62]
Thanks for a great package!

I'm using this together with preact and I'm wondering what kind of actions really get captured. In [your example](https://github.com/captbaritone/raven-for-redux/blob/master/example/index.js) I can see that you're throwing errors inside the reducer, outside of the reducer and inside a click event. To me it looks like you're capturing most of thrown errors, but is there any cases where I need to handle it "manually" on the client side? It would be great if this could be clarified in the docs. Thanks!

**Comment by captbaritone** [comment]
The context will be attached to any error that Raven captures. Generally this would be any uncaught error.

Want to open a pull request to add some clarification to the Readme?
