### ISSUE TITLE
Add note about mutating data to documentation

### ISSUE THREAD

**Issue by captbaritone** [captbaritone/raven-for-redux#7]
As @ChrisSargent found in #5, it's very easy to accidentally mutate an object in one of our optional transform functions. This can lead to very confusing bugs. We could help avoid this by adding a reminder in our documentation.

**Comment by captbaritone** [comment]
This is probably not so important any more. After merging #8, the action and state are only ever transformed once, when the error is reported.

**Comment by ChrisSargent** [comment]
True, but is it possible it might not be an app-crashing error and therefore it would still be best to not mutate the state? I think a simple 'Remember not to mutate your state here, if your state will continue to be used'

**Comment by captbaritone** [comment]
Good point. Fixed.
