### ISSUE TITLE
Is it possible to capture only certain errors? 

### ISSUE THREAD

**Issue by oliv9286** [captbaritone/raven-for-redux#80]
I was reading through the docs and saw the instruction asking to do `Raven.install()`.
Some background context: my app is placed on a page that contains other projects as well, I don't want to use `Raven.install()` and all errors on the page, including the ones thrown from the other projects. 

Ravenjs itself provides a way to 
```
try {
... some piece of code
} catch(e) {
Raven.captureException(e)
}
```

Is this something that can be done using this middleware?

**Comment by captbaritone** [comment]
Yeah, if you just omit the "install" step, it should work just fine. Give it a try and let me know if it works.

**Comment by captbaritone** [comment]
I'm going to close this for now. Feel free to reply if this doesn't work for you.
