### ISSUE TITLE
GDPR: Filter data before sending

### ISSUE THREAD

**Issue by johdah** [captbaritone/raven-for-redux#97]
Is it possible to filter the data before sending it to Sentry? We store user information in the redux store but for obvious reasons would prefer not to send it to Sentry. For example a rule could be to exclude state.user from what's sent to sentry.

**Comment by Vannevelj** [comment]
I think you're looking for this? https://github.com/captbaritone/raven-for-redux#statetransformer-function

**Comment by johdah** [comment]
Ah, thanks I missed that one.
